### ISSUE TITLE
UI - Separate search filters listview from background

### ISSUE THREAD

**Issue by utkarshmttl** [utkarshmttl/eModules#13]
The listview (containing filters) appearing on clicking the search icon overlays on background main recyclerview (containing list of questions). In some devices, a portion of the background is visible which is a little bit confusing. There can be multiple ways to tackle this such as making the entire background (including pull up tab if possible?) a little dull/greyish/slightly transparent. Or add border to top listview or open to suggestions.

**Comment by kungfucat** [comment]
This issue is resolved in pull request #14 .
